# Generated by Django 5.0.6 on 2024-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('F_name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
