# Generated by Django 5.0.6 on 2024-08-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
                ('r_description', models.TextField()),
                ('r_image', models.ImageField(upload_to='recipe_img')),
            ],
        ),
    ]
