# Generated by Django 5.0.6 on 2024-09-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='r_video',
            field=models.FileField(blank=True, null=True, upload_to='recipe_videos'),
        ),
    ]
